#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the beautifulBinaryString function below.
def beautifulBinaryString(b):
    flag = True
    a = '010'
    counter = 0
    i = 0
    while(i < len(b) - 2):
        if b[i:i + 3] == a:
            counter += 1
            i += 3
        else:
            i += 1
    return counter

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    b = input()

    result = beautifulBinaryString(b)

    fptr.write(str(result) + '\n')

    fptr.close()
