#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the funnyString function below.
def funnyString(s):
    result = [ord(i) for i in s]
    new_result = result[::-1]
    for i in range(len(result) - 1):
        if abs(result[i + 1] - result[i]) != abs(new_result[i + 1] - new_result[i]):
            return "Not Funny"
    else:
        return "Funny"        


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s = input()

        result = funnyString(s)

        fptr.write(result + '\n')

    fptr.close()
