#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the workbook function below.
def workbook(n, k, arr):
    count = 0
    page_num = {}
    pages = 1
    for i in range(n):
        pages_req = math.ceil(arr[i]/k)
        qstion = 1
        for j in range(pages, pages + pages_req):
            page_num[j] = [l for l in range(qstion, min(arr[i] + 1, qstion + k))]
            qstion += k
        pages += pages_req
    for i in range(1, pages):
        if i in page_num[i]:
            count += 1
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    arr = list(map(int, input().rstrip().split()))

    result = workbook(n, k, arr)

    fptr.write(str(result) + '\n')

    fptr.close()
