#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the separateNumbers function below.
def separateNumbers(s):
    for a in range(1, math.ceil(len(s)/2)):
        string = ''
        num = int(s[:a])
        while((len(string) <= len(s))):
            string += str(num)
            num += 1
            if string == s:
                return "YES" + " " + s[:a]
    else:
        return "NO"




if __name__ == '__main__':
    q = int(input())

    for q_itr in range(q):
        s = input()

        print(separateNumbers(s))
