#!/bin/python3

import math
import os
import random
import re
import sys
from statistics import mode
from collections import Counter
# Complete the isValid function below.
def isValid(s):
    result = []
    s = Counter(s)
    for i in s:
        result.append(s[i])
    if len(set(result)) == 2 and result.count(1) == 1:
        result.pop(result.index(1))
    sum = 0
    for i in result:
        sum += i - min(result)
    if sum == 1 or sum == 0:
        return "YES"
    else:
        return "NO"
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = isValid(s)

    fptr.write(result + '\n')

    fptr.close()
