#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumNumber function below.
def minimumNumber(n, password):
    num = len(password)
    flag_n = True
    flag_l = True
    flag_u = True
    flag_s = True
    s = list("!@#$%^&*()-+")
    u = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    l = list("abcdefghijklmnopqrstuvwxyz")
    n = list("0123456789")
    for i in password:
        if i in s:
            flag_s = False
        if i in l:
            flag_l = False
        if i in u:
            flag_u = False
        if i in n:
            flag_n = False
    if num > 6:
        return flag_l + flag_n + flag_s + flag_u
    else:
        return max(6 - num, flag_l + flag_n + flag_s + flag_u)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    password = input()

    answer = minimumNumber(n, password)

    fptr.write(str(answer) + '\n')

    fptr.close()
