#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the theLoveLetterMystery function below.
def theLoveLetterMystery(s):
    n = len(s)
    if n == 0:
        a = s[:int(n/2)]
        b = s[int(n/2):]
        a = [ord(i) for i in a]
        b = [ord(i) for i in b][::-1]
        su = 0
        for i in range(len(a)):
            su += max(a[i], b[i]) - min(a[i], b[i])
        return su
    else:
        a = s[:math.ceil(n/2)]
        b = s[math.floor(n/2):]
        a = [ord(i) for i in a]
        b = [ord(i) for i in b][::-1]
        su = 0
        for i in range(len(a)):
            su += max(a[i], b[i]) - min(a[i], b[i])
        return su

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s = input()

        result = theLoveLetterMystery(s)

        fptr.write(str(result) + '\n')

    fptr.close()
